version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - embeddedstructfieldcheck
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 120
      statements: 70
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - paramTypeCombine
        - unnamedResult
      enabled-tags:
        - diagnostic
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 150
    misspell:
      locale: US
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: atomic
        - name: blank-imports
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: datarace
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: enforce-map-style
        - name: enforce-slice-style
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: identical-branches
        - name: if-return
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: optimize-operands-order
        - name: package-comments
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-import-alias
        - name: string-of-int
        - name: struct-tag
        - name: superfluous-else
        - name: time-date
        - name: time-naming
        - name: unchecked-type-assertion
        - name: unexported-return
        - name: unnecessary-format
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unhandled-error
        - name: use-errors-new
        - name: use-fmt-print
        - name: useless-break
        - name: var-declaration
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gosec
          - lll
        path: _test\.go
    paths:
      - storage/addons/sqldb/testfixtures
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - example.com/aaa/bbb/
  exclusions:
    generated: lax
    paths:
      - storage/addons/sqldb/testfixtures
      - third_party$
      - builtin$
      - examples$
